OA-7: Setup tests for omod, test MetadataController
openmrs/openmrs-module-oauth2 pull request #24
Opened 2019-10-23 23:57 UTC by pjsier

This PR sets up some basic tests for the `omod` layer on the `MetadataController` to implement OA-7: https://issues.openmrs.org/browse/OA-7

I wasn't sure how far to go in testing the values inside the controller, and I'm happy to build those out more if you're looking for more than regression tests. I don't normally work in Java, and I think I have my editor setup with the style configuration, but if I'm doing not doing anything the way it should be done let me know, thanks!

2020-01-11 04:23 UTC, Devanshk9 commented
Hi @pjsier  please resolve merge conflicts

2020-01-11 04:34 UTC, pjsier commented
@Devanshk9 just updated, let me know if it needs anything else, thanks!

2020-01-11 04:49 UTC, Devanshk9 commented
Ok now merge conflict it resolved😊
thanks

2020-01-11 04:51 UTC, Devanshk9 commented
Please also squash your commits once there are no changes required.

2020-01-11 22:22 UTC, pjsier commented
@Devanshk9 rebased now so it should be fixed, thanks!

2020-03-16 18:04 UTC, ibacher commented on omod/src/test/java/org/openmrs/module/oauth2/web/controller/MetadataControllerTest.java
> +		assertNotNull(controller);
I'd eliminate this test, which is really just verifying that Spring works and not a useful test of any module-specific functionality.

2020-03-16 18:05 UTC, ibacher requested changes
@pjsier This looks useful. Could you get rid of the one one test? Then I'll be happy with it.

2020-03-22 15:00 UTC, pjsier commented
@ibacher just updated, thanks for the review!

2020-03-23 12:52 UTC, ibacher approved these changes

2020-03-23 12:52 UTC, merged